name: Changelog RC

on:
  release:
    types: [
      prereleased
    ]

jobs:
  write-changelog-rc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Write changelogs
        run: yarn changelog
      - name: Get latest release
        id: latest_rc_id
        run: |
          echo ::set-output name=id::$( \
            curl \
              --url "https://api.github.com/repos/${{ github.repository }}/releases" \
              --header "accept: application/vnd.github.v3+json" \
              --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              -sL | \
            jq --raw-output '.[-1].id'
          )
      - name: Update release
        run: |
          cat << EOF > __rc_data.json
          {
            "draft": false,
            "prerelease": false,
            "body":"
          EOF
          cat CHANGELOG.md | sed -z 's/\n/\\n/g' >> __rc_data.json
          echo \"} >> __rc_data.json
          cat __rc_data.json
          curl \
            --request PATCH "https://api.github.com/repos/${{ github.repository }}/releases/${{ steps.latest_rc_id.outputs.id }}" \
            --header "accept: application/vnd.github.v3+json" \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data @__rc_data.json
